package unit

import "github.com/jxman78/wiki-brain/internal/foundation/textmatch"

// LocateUnitBounds resolves a unit's absolute line_start/line_end from the
// model's reported line numbers (reportedStart/reportedEnd) plus the verbatim
// anchor text it claims sits on those lines (firstAnchor/lastAnchor).
//
// Neither signal is trusted alone:
//   - A reported line number alone (prompt_version v2/v3) let a miscounted
//     index silently swallow a dozen unrelated lines — nothing checked it.
//   - Anchor text alone, searched blind across the whole segment
//     (prompt_version v4), can't tell the program which physical line the
//     model actually meant: MatchFragment is applied one physical mdLines
//     row at a time, so any anchor the model wrote by blending two adjacent
//     rows (e.g. a heading on its own line immediately followed, after a
//     blank line, by its body) can never match any single row and the unit
//     is lost — even though the model's underlying extraction was correct.
//
// v5 has the model report both: the claimed line number is first verified by
// checking the anchor text actually appears on that specific mdLines row
// (verifyReportedLine, reusing textmatch.MatchFragment's exact-then-fuzzy
// match). A verified report is trusted directly — no scanning needed, and it
// disambiguates duplicate line content the blind scan can't. Only when the
// report fails verification (wrong number, or genuinely hallucinated/
// cross-line text) does resolution fall back to the v4 line-by-line scan
// below, so a bad report degrades to exactly today's behavior rather than
// ever being trusted uncritically.
//
// cursor hints where the v4 fallback should start searching for firstAnchor
// (pass seg.LineStart for the first unit in a segment, then each call's
// returned nextCursor for the following one) to disambiguate repeated line
// content when no verified report is available — it is only a search-order
// hint, not an enforced non-overlap constraint, since some segments
// legitimately have a broader "overview" unit whose span contains narrower
// sibling units. If nothing matches from cursor onward, the search restarts
// from seg.LineStart once, to tolerate the model not listing units in strict
// document order.
//
// Every candidate line is matched independently line-by-line (never against
// the segment as one blob) so the resolved boundary can only ever land on an
// actual line within the segment — the exact failure mode that let one bad
// unit swallow a dozen unrelated ones is structurally impossible here.
func LocateUnitBounds(mdLines []string, seg Segment, reportedStart int, firstAnchor string, reportedEnd int, lastAnchor string, cursor int) (lineStart, lineEnd, nextCursor int, ok bool) {
	lineStart, ok = verifyReportedLine(mdLines, seg, reportedStart, firstAnchor)
	if !ok {
		lineStart, ok = findAnchorLine(mdLines, cursor, seg.LineEnd, firstAnchor)
		if !ok && cursor != seg.LineStart {
			lineStart, ok = findAnchorLine(mdLines, seg.LineStart, seg.LineEnd, firstAnchor)
		}
	}
	if !ok {
		return 0, 0, cursor, false
	}

	lineEnd, ok = verifyReportedLine(mdLines, seg, reportedEnd, lastAnchor)
	if !ok || lineEnd < lineStart {
		lineEnd, ok = findAnchorLine(mdLines, lineStart, seg.LineEnd, lastAnchor)
	}
	if !ok {
		return 0, 0, cursor, false
	}

	return lineStart, lineEnd, lineEnd + 1, true
}

// WidenBoundsFromPoints extends [lineStart, lineEnd] to cover every point
// whose own reported anchor can be located within the segment.
//
// The root cause this closes: a unit's knowledge points are generated by
// broadly synthesizing across whatever content the model judged relevant,
// while the unit's own line_start/line_end is a separate, narrower
// transcription task ("what line does this topic's heading/first row sit
// on") — nothing forces the two to agree. In practice this let a unit
// declare e.g. just a table's header row while its points quietly drew
// facts from rows several lines further down, which VerifyReportedLine
// alone can never catch (the anchor it's given genuinely exists — it's
// just narrower than what the unit's content actually spans). Prompt
// version v6 has the model report the same line_start/first_line_anchor/
// line_end/last_line_anchor shape per point, scoped to that one point's own
// source material; locating each and folding it into the union recovers
// the true span without trusting the model's unit-level judgment alone.
//
// A point whose anchor is empty (prompt_version v5 didn't ask for per-point
// anchors, so these fields came back zero-valued for units extracted under
// it; unit_extract_retry.md was later synced to the same v6 per-point-anchor
// shape as unit_extract.md, so this now only applies to that older v5 data)
// or fails to locate contributes nothing — its content is still kept by the
// caller, it just isn't trusted to widen the boundary, so this degrades to a
// no-op exactly where it doesn't apply.
func WidenBoundsFromPoints(mdLines []string, seg Segment, lineStart, lineEnd int, points []llmPoint) (int, int) {
	cursor := seg.LineStart
	for _, p := range points {
		if p.FirstLineAnchor == "" || p.LastLineAnchor == "" {
			continue
		}
		pStart, pEnd, nextCursor, ok := LocateUnitBounds(mdLines, seg, p.LineStart, p.FirstLineAnchor, p.LineEnd, p.LastLineAnchor, cursor)
		if !ok {
			continue
		}
		cursor = nextCursor
		if pStart < lineStart {
			lineStart = pStart
		}
		if pEnd > lineEnd {
			lineEnd = pEnd
		}
	}
	return lineStart, lineEnd
}

// verifyReportedLine checks the model's claimed line number is within the
// segment and that the anchor text it gave actually appears on that specific
// mdLines row. Returns ok=false for any unverifiable report (out of range,
// out of the segment, or anchor not found there) so the caller falls back to
// scanning instead of trusting an unverified number.
func verifyReportedLine(mdLines []string, seg Segment, reported int, anchor string) (int, bool) {
	if reported < seg.LineStart || reported > seg.LineEnd || reported < 1 || reported > len(mdLines) {
		return 0, false
	}
	if _, _, _, ok := textmatch.MatchFragment(mdLines[reported-1], anchor); !ok {
		return 0, false
	}
	return reported, true
}

// findAnchorLine scans mdLines[from-1 : to] (1-based, inclusive) and returns
// the absolute line number of the first line containing anchor.
func findAnchorLine(mdLines []string, from, to int, anchor string) (int, bool) {
	if from < 1 {
		from = 1
	}
	if to > len(mdLines) {
		to = len(mdLines)
	}
	for i := from; i <= to; i++ {
		if _, _, _, ok := textmatch.MatchFragment(mdLines[i-1], anchor); ok {
			return i, true
		}
	}
	return 0, false
}
